### ISSUE TITLE
240 x 320 setup

### ISSUE THREAD

**Issue by scott1423** [afiskon/stm32-st7735#2]
Hi
  I have been using your C code for my 1.8" st7735, and works really well. I purchased a 2.8" 240x320 ST7735 and hoped it was just a matter of changing the MaxY and X width.  Do you have a bit of code to setup the 240 x 320? 

Many thanks
Scott

**Comment by afiskon** [comment]
Hello @scott1423 

According to the datasheet ST7735 doesn't support 240x320 resolution http://www.displayfuture.com/Display/datasheet/controller/ST7735.pdf

I guess your display may be in fact a ILI9341 module because 240x320 and 2.8" are common for these displays. There is a separate library for ILI9341 displays https://github.com/afiskon/stm32-ili9341

If you are sure you are not dealing with ILI9341 could you please upload a picture of your module and/or provide a URL where it was purchased?

**Comment by scott1423** [comment]
Hi
  Thanks for the below.
You are correct, it is a ILI9341. On the add it displayed baritones from 1.4 to 2.8, and mentioned it’s a st7735. But further looking into it it says it’s the ILI9341. That’s what I get for not looking at it properly:)

Your library I use for the st7735 is in c as I don’t write my processor (stm32L4) in C++. Is this code for the ILI9241 also in C? As that would be perfect.

Many thanks again 

Best regards
Scott

**Comment by afiskon** [comment]
Yes, the ILI9341 library is also written in C.

**Comment by scott1423** [comment]
Many thanks

Best regards
Neil
